### ISSUE TITLE
Can't use `Annotated` with `ForwardRef`

### ISSUE THREAD

**Issue by Kludex** [fastapi/fastapi#13056]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

The following code doesn't generate the correct OpenAPI json:

```py
from __future__ import annotations

from dataclasses import dataclass
from typing import Annotated

from fastapi import Depends, FastAPI

app = FastAPI()


def get_potato() -> Potato:
    return Potato(color='red', size=10)


@app.get('/')
async def read_root(potato: Annotated[Potato, Depends(get_potato)]):
    return {'Hello': 'World'}


@dataclass
class Potato:
    color: str
    size: int
```

If we move the `Potato` up, or remove the `Annotated`, then it works as expected.

**Comment by rahmanshamit** [comment]
The issue is with 'from __future__ import annotations' and 'Annotated[Potato, Depends(get_potato)]', right?
Since Potato class is defined later, in the read_root function __future__.annotations may be trying to store Potato as a string literal, but then Annotated wraps the Potato type, which FastAPI needs to unwrap and evaluate during schema generation, generating the wrong OpenAPI json?
What does the generated json look like?

**Comment by samuelcolvin** [comment]
No I don't think so. I think it's just the use of `from __future__ import annotations`, I think you're get the same error if `Potato` was defined earlier.

Also, please format your message properly to make it easier to read.

**Comment by Kludex** [comment]
> [...] I think you'll get the same error if Potato was defined earlier.

No, the problem here is `Potato` after.

> What does the generated json look like? Do we get 'Annotated[Potato, Depends(get_potato)]' rather than the actual type?

The `potato` is a query parameter on the generated OpenAPI. But you can run it, and check by yourself... 👀

**Comment by Viicos** [comment]
Probably FastAPI needs to implement its own forward annotation evaluation logic, and perhaps a "rebuild" pattern for such use cases. Currently, upon creation of the API route, the `Dependant` instance is not defined correctly:

```python
from __future__ import annotations

from dataclasses import dataclass
from typing import Annotated

from fastapi import Depends, FastAPI

app = FastAPI()

def get_potato() -> Potato:
    return Potato(color='red', size=10)


@app.post('/')
async def read_root(potato: Annotated[Potato, Depends(get_potato)]):
    return {'Hello': 'World'}


@dataclass
class Potato:
    color: str
    size: int

app.routes[-1].dependant
#> Dependant(query_params=[ModelField(field_info=Query(PydanticUndefined), name='potato', mode='validation')] ,...)
``` 

Also note that the logic to evaluate forward annotations is too naive:

https://github.com/fastapi/fastapi/blob/d7f88623e1304667c67da17dfd278b5099522ef9/fastapi/dependencies/utils.py#L247-L251

and as such the following also fails even if `Potato` is defined *before*:

```python
@dataclass
class Potato:
    color: str
    size: int

@app.post('/')
async def read_root(potato: Annotated["Potato", Depends(get_potato)]):
    return {'Hello': 'World'}
```

If possible, FastAPI should avoid relying on Pydantic's internals ([e.g. `eval_type_lenient`](https://github.com/fastapi/fastapi/blob/d7f88623e1304667c67da17dfd278b5099522ef9/fastapi/_compat.py#L57), which we had to deprecate instead of removing it even if it was an internal function). Our type evaluation logic is subject to changes as we'll have to adapt to PEP 649.

**Comment by akoshel** [comment]
Hi all
I encountered a similar issue with PydanticUndefinedAnnotation in a FastAPI project. Here's my setup:

Project Structure
```
project/
├── __init__.py (empty)
├── app.py
├── models.py
└── deco.py
```
deco.py
```python
from typing import TypeVar, ParamSpec
from functools import wraps
from collections.abc import Callable

T = TypeVar("T")
P = ParamSpec("P")

def my_deco(func: Callable[P, T]) -> Callable[P, T]:
    @wraps(func)
    def wrapper(*args: P.args, **kwargs: P.kwargs) -> T:
        return func(*args, **kwargs)
    return wrapper
```
models.py
```python
from pydantic import BaseModel

class MyQuery(BaseModel):
    query: list[str]

class MyResponse(BaseModel):
    ...
```
app.py

```python
from __future__ import annotations

from deco import my_deco
from fastapi import FastAPI
from models import MyQuery, MyResponse

app = FastAPI()

@app.post("/query", response_model=MyResponse)
@my_deco
async def query(query: MyQuery) -> MyResponse:
    return MyResponse()
 ```
Steps to Reproduce
Run the application with uvicorn:

```bash
uvicorn app:app --host 0.0.0.0 --port 8000
pydantic.errors.PydanticUndefinedAnnotation: name 'MyQuery' is not defined
```

Observations
Removing from `__future__ ` import annotations resolves the issue.
Removing the @my_deco decorator also resolves the issue.
This behavior seems to be related to how `__future__.annotations` interacts with decorators and the way FastAPI/Pydantic processes type annotations.

**Comment by abhiaagarwal** [comment]
I ran into this issue with caused debugging hell, there's a function already part of the standard library that solves most of the complicated logic: `https://typing-extensions.readthedocs.io/en/latest/index.html#typing_extensions.get_annotations`.

**Comment by adriangb** [comment]
Here's another repro:

```python
from __future__ import annotations

from typing import TYPE_CHECKING, Annotated

from fastapi import APIRouter, Depends, FastAPI
from fastapi.testclient import TestClient

if TYPE_CHECKING:
    from httpx import AsyncClient

router = APIRouter()


@router.get("/test")
async def ping(client: Annotated[AsyncClient, Depends(lambda: AsyncClient())]) -> str:
    resp = await client.get('http://example.com')
    resp.raise_for_status()
    return f"Got {len(resp.text)} bytes"


def create_app() -> FastAPI:
    app = FastAPI()
    app.include_router(router)
    return app


async def test() -> None:
    from httpx import AsyncClient

    async with AsyncClient() as client:
        app = create_app()
        client = TestClient(app)

        response = client.get("/test")
        assert response.status_code == 200, f"{response.status_code=}: {response.text=}"


if __name__ == "__main__":
    import anyio

    anyio.run(test)
```

**Comment by pachewise** [comment]
Hi everyone, what versions of Python/fastapi are you running? 

Running the [provided snippet](https://github.com/fastapi/fastapi/issues/13056#issue-2729953389) with Py 3.11.4, fastapi `master`, I get the traceback below, can OP confirm that's what they're getting, too?

<details><summary>Traceback</summary>

<p>

```python-traceback
Traceback (most recent call last):
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 864, in _resolve_forward_ref
    obj = _typing_extra.eval_type_backport(obj, globalns=self._types_namespace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/_internal/_typing_extra.py", line 279, in eval_type_backport
    return _eval_type_backport(value, globalns, localns, type_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/_internal/_typing_extra.py", line 303, in _eval_type_backport
    return _eval_type(value, globalns, localns, type_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/_internal/_typing_extra.py", line 332, in _eval_type
    return typing._eval_type(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/typing.py", line 371, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/typing.py", line 877, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'Potato' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pachewise/repos/fastapi/example.py", line 15, in <module>
    @app.get('/')
     ^^^^^^^^^^^^
  File "/Users/pachewise/repos/fastapi/fastapi/routing.py", line 994, in decorator
    self.add_api_route(
  File "/Users/pachewise/repos/fastapi/fastapi/routing.py", line 933, in add_api_route
    route = route_class(
            ^^^^^^^^^^^^
  File "/Users/pachewise/repos/fastapi/fastapi/routing.py", line 554, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/repos/fastapi/fastapi/dependencies/utils.py", line 285, in get_dependant
    param_details = analyze_param(
                    ^^^^^^^^^^^^^^
  File "/Users/pachewise/repos/fastapi/fastapi/dependencies/utils.py", line 488, in analyze_param
    field = create_model_field(
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/repos/fastapi/fastapi/utils.py", line 96, in create_model_field
    return ModelField(**kwargs)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "/Users/pachewise/repos/fastapi/fastapi/_compat.py", line 111, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
                                           ^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2024, in _annotated_schema
    source_type, *annotations = self._get_args_resolving_forward_refs(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _get_args_resolving_forward_refs
    args = tuple([self._resolve_forward_ref(a) if isinstance(a, ForwardRef) else a for a in args])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 886, in <listcomp>
    args = tuple([self._resolve_forward_ref(a) if isinstance(a, ForwardRef) else a for a in args])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pachewise/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 866, in _resolve_forward_ref
    raise PydanticUndefinedAnnotation.from_name_error(e) from e
pydantic.errors.PydanticUndefinedAnnotation: name 'Potato' is not defined

For further information visit https://errors.pydantic.dev/2.9/u/undefined-annotation
```
</p>
</details>

As to what the fix should be -- this looks like it is failing in the TypeAdapter calls (at least in my setup), though it would likely fail in otherplaces Is TypeAdapter expected to handle ForwardRefs? Will be doing some more debugging later, but we may not be able to fix this without Pydantic changes

**Comment by ashb** [comment]
Most minimal repro case I can come up with:

```python
# from __future__ import annotations

from fastapi import FastAPI, Depends, Request


app = FastAPI()


class Foo:
    def __init__(self):
        breakpoint()
        ...

    async def __call__(self, request: Request):
        breakpoint()
        return 123


@app.get("/foobar", dependencies=[Depends(Foo())])
def foo():
    return "hi"
```

Fast API version: 0.115.11
Python version: Python 3.12.7

**Comment by yvallois** [comment]
> Most minimal repro case I can come up with:
> 
> from __future__ import annotations
> 
> from fastapi import FastAPI, Depends, Request
> 
> 
> app = FastAPI()
> 
> 
> class Foo:
>     def __init__(self):
>         breakpoint()
>         ...
> 
>     async def __call__(self, request: Request):
>         breakpoint()
>         return 123
> 
> 
> @app.get("/foobar", dependencies=[Depends(Foo())])
> def foo():
>     return "hi"
> Fast API version: 0.115.11 Python version: Python 3.12.7

This error seems different from the one shown by Kludex. In the case of kludex, the call to __globals__ doesn't return Potato because it's defined after the endpoint. In your case, Foo() has no __globals__ attribute and an empty dictionary is used to resolve the injection.
see: https://github.com/fastapi/fastapi/discussions/13485

**Comment by srcolinas** [comment]
Are there any plans to fix the issue?

**Comment by UnkownHunter** [comment]
I have referred and understood what is the problem.@adriangb please help me understand what is that this is referring to https://github.com/fastapi/fastapi/issues/13056#issuecomment-2616362994. if you would give me something that I could refer to would be very  helpful...

**Comment by bayoumi17m** [comment]
I've explored the codebase, and although it seems #14557 and #14703 were associated with this issue to attempt to fix. I have some ideas on making the check a bit more robust so we can cover variations such as `typing.Annotated` or even type aliasing.

If there is interest, I can take a stab and open a PR in the next day or so?

**Comment by AhsanSheraz** [comment]
I've opened PR #15096 with a fix for this issue.

**Root cause:** When `from __future__ import annotations` is active, `Annotated[SomeClass, Depends(...)]` becomes a string. If `SomeClass` is defined after the route decorator, it's not available at decoration time, so the full `Annotated` string can't be resolved. FastAPI loses the `Depends` metadata and incorrectly treats the parameter as a query parameter.

**Fix:** A lenient namespace evaluation strategy — when strict resolution fails, undefined names resolve to `Any`, preserving the `Annotated` structure so FastAPI can extract the `Depends` metadata. The lenient fallback only applies for `Depends` metadata; other metadata types (`Query`, `Body`, etc.) still use the existing resolution path since they need the actual type.

**Comment by deeptireddy-lab** [comment]
Severity: P2
Component: OpenAPI generation
Repro steps: 
The following code doesn't generate the correct OpenAPI json:

```python
from __future__ import annotations

from dataclasses import dataclass
from typing import Annotated

from fastapi import Depends, FastAPI

app = FastAPI()


def get_potato() -> Potato:
    return Potato(color='red', size=10)


@app.get('/')
async def read_root(potato: Annotated[Potato, Depends(get_potato)]):
    return {'Hello': 'World'}


@dataclass
class Potato:
    color: str
    size: int
```

Duplicates: #15234, #14952, #15300, #13056

**Comment by tiangolo** [comment]
We'll continue tracking this internally, I'll close this one to prevent more automated AI generated PRs that only add to our overhead. ☕ 

https://fastapi.tiangolo.com/contributing/#automated-code-and-ai
