### ISSUE TITLE
Incorrect handling of non utf-8 data in body in case of a validataion error

### ISSUE THREAD

**Issue by ph4** [fastapi/fastapi#13111]
### Privileged issue

- [X] I'm @tiangolo or he asked me directly to create an issue here.

### Issue Content

There was no way to report actual issue by the rules so I had to lie about being able to do so...

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "REDACTED\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "REDACTED\.venv\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "REDACTED\.venv\Lib\site-packages\fastapi\routing.py", line 315, in app
    raise validation_error
fastapi.exceptions.RequestValidationError: [{'type': 'model_attributes_type', 'loc': ('body',), 'msg': 'Input should be a valid dictionary or object to extract fields from', 'input': b'----cpp-httplib-multipart-data-UxL5MB5nIRg5wqYk\r\nContent-Disposition: form-data; name="metadata"\r\nContent-Type: application/json\r\n\r\n{"started":1735320698,"length_seconds":3}\r\n----cpp-httplib-multipart-data-UxL5MB5nIRg5wqYk\r\nContent-Disposition: form-data; name="metadata"; filename="main.ogg"\r\nContent-Type: audio/ogg\r\n\r\nOggS\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x81Z\x97E\x00\x00\x00\x00\x0b\xffmn\x01\x13OpusHead\x01\x028\x01\x80>\x00\x00\x00\x00\x00OggS\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x81Z\x97E\x01\x00\x00\x00\xf3sR\x98\x01\'OpusTags\x17\x00\x00\x00recorder ogg-opus 0.0.1\x00\x00\x00\x00OggS\x00\x00\xc0\xf3\x00\x00\x00\x00\x00\x00\x81Z\x97E\x02\x00\x00\x00\xd2\xf2\x8d<A\x14\x1b\r\n----cpp-httplib-multipart-data-UxL5MB5nIRg5wqYk--\r\n'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "REDACTED\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACTED\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACTED\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "REDACTED\.venv\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "REDACTED\.venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "REDACTED\.venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "REDACTED\.venv\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "REDACTED\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "REDACTED\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "REDACTED\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "REDACTED\.venv\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "REDACTED\.venv\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "REDACTED\.venv\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "REDACTED\.venv\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "REDACTED\.venv\Lib\site-packages\starlette\_exception_handler.py", line 75, in wrapped_app
    response = await handler(conn, exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACTED\.venv\Lib\site-packages\fastapi\exception_handlers.py", line 25, in request_validation_exception_handler
    content={"detail": jsonable_encoder(exc.errors())},
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACTED\.venv\Lib\site-packages\fastapi\encoders.py", line 303, in jsonable_encoder
    jsonable_encoder(
  File "REDACTED\.venv\Lib\site-packages\fastapi\encoders.py", line 289, in jsonable_encoder
    encoded_value = jsonable_encoder(
                    ^^^^^^^^^^^^^^^^^
  File "REDACTED\.venv\Lib\site-packages\fastapi\encoders.py", line 318, in jsonable_encoder
    return ENCODERS_BY_TYPE[type(obj)](obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "REDACTED\.venv\Lib\site-packages\fastapi\encoders.py", line 59, in <lambda>
    bytes: lambda o: o.decode(),
                     ^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 335: invalid start byte
```

using `o.decode(errors='ignore')` seems to fix the issue

**Comment by Teut2711** [comment]
Well, the issue is too vague. You should at least share what string is causing the issue.
